### ISSUE TITLE
Table: "one line" answer space enlarged if any amount of student-visible content is added

### ISSUE THREAD

**Issue by bpugliese** [PASCOscientific/cpd-oxygen-framework#42]
When cells in a table are defined as one-line answers, a one line answer that is entered as a student-visible value takes up more space than a one line answer:
![image](https://user-images.githubusercontent.com/76796068/125701689-cecf4b8a-98ad-4371-afe1-a508c8dc9dc8.png)
Possible solutions: 1.5 line answer? Or reduce padding only on student-visible cell contents?

**Comment by bpugliese** [comment]
Update: This weird gap shows up no matter how many "lines" I set for answer. Seems like adding text is adding padding.

**Comment by jonathanhanna** [comment]
Which lab is this?

**Comment by bpugliese** [comment]
Blockly_Ext_Energy_Flow, let me push it

-Barbara

**Comment by jonathanhanna** [comment]
Easy fix. Just remove the `outputclass='one-line'` from those two cells. In fact, you can remove this from all of the cells because the transformation provides one-line of space by default. The "one-line" outputclass only exists for answer space after questions, not for tables.
