### ISSUE TITLE
Request to color hyperlinks the typical blue in PDF and DOCX outputs

### ISSUE THREAD

**Issue by bpugliese** [PASCOscientific/cpd-oxygen-framework#46]
Hyperlinks work in digital outputs but are not apparent; if possible please add blue style to hyperlinks in all outputs - maybe even an underline too - or is that ugly? Here's an example of a hyperlink in a PDF; it doesn't jump out as a clickable link:
![image](https://user-images.githubusercontent.com/76796068/148271655-ced696c0-ce45-4ec2-b5e7-8dae9968ae77.png)

**Comment by jonathanhanna** [comment]
I wouldn't use blue since that wouldn't work well for grayscale printing. Underlining is an outdated style. How about making the text bold?

**Comment by bpugliese** [comment]
Bold is fine – works just as well as a cue to click!

-Barbara

**Comment by jonathanhanna** [comment]
Fixed in e9bbdac396bb6fa2d48ce1f53b5d1a91d0e53f92. However, I was not able to make the hyperlink bold in the docx file. The docx plugin doesn't currently recognized hyperlinks, so unfortunately there's not any way for me to apply a style to it.

**Comment by jonathanhanna** [comment]
Fixed the docx issue in 06915269f8dc953e1f8c2eb1a5f2a8e7a1ef539d.
