### ISSUE TITLE
In-line images do not scale in figure titles

### ISSUE THREAD

**Issue by bpugliese** [PASCOscientific/cpd-oxygen-framework#47]
I've been using in-line images for numbered figure references - works fine in a paragraph - but does not scale to line height in a figure title: 
![image](https://user-images.githubusercontent.com/76796068/151429714-63fceb61-8d3b-4dfd-9f31-9f15df44bacb.png)

**Comment by bpugliese** [comment]
Project: https://github.com/PASCOscientific/Code_Cooling_Breeze

**Comment by jonathanhanna** [comment]
That's weird. What happens if you wrap all the text in another element, such as `<ph>`? For example:
`<title><ph>My figure title.</ph></title>`

I'm out of the office today and tomorrow, so I won't be able to take a look until Monday.

**Comment by jonathanhanna** [comment]
One other thing. What happens if you try to change the size of the image? Try adding a height or width attribute and change it to something small, like 20 px.

**Comment by bpugliese** [comment]
<ph> doesn’t have an effect; changing size does change size but the image position looks like it defaults center aligned… “1” has the fixed size but “2” does not:

***@***.***

-Barbara

**Comment by jonathanhanna** [comment]
Fixed in 16e3307beba8f16cc5d5a3fb9d8ce3aeab51ac04.
